---
name: Auto approve

on:
  pull_request_target:

jobs:
  approve:
    name: Approve
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write
    if: github.event.label.name == 'auto-approve'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Approve
        uses: hmarr/auto-approve-action@v3
