---
name: Auto approve

on:
  pull_request:
    types: [review_requested, labeled]
  workflow_dispatch:
    inputs:
      pull-request-number:
        description: "Pull Request Number"
        type: string
        required: true

jobs:
  approve:
    name: Approve
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write
    if: github.event.label.name == 'auto-approve' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Approve
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number || github.event.inputs.pull-request-number }}
