---
name: Labeler

on:
  pull_request:

jobs:
  auto-labeling:
    name: Auto-labeling
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Labeler
        uses: actions/labeler@v6
