---
name: GitHub Profile 3D Contrib

on:
  schedule:
    # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    env:
      BRANCH_NAME: feature/generate-github-profile-3d-contrib
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Profile 3d contrib
        uses: yoshi389111/github-profile-3d-contrib@5b718734e8da645411919f0ae9ab9e7f9377158f # v0.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Generate GitHub App Token
        id: app_token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3
        with:
          app-id: ${{ secrets.GHA_APP_ID }}
          private-key: ${{ secrets.GHA_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        id: cpr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "${{ env.BRANCH_NAME }}"
          base: main
          title: "Update profile-3d-contrib"
          body: "Automated update of profile-3d-contrib files."

      - name: Pull Request Automerge
        if: steps.cpr.outputs.pull-request-number
        env:
          GH_TOKEN: ${{ steps.app_token.outputs.token }}
        run: |
          PR_NUMBER="${{ steps.cpr.outputs.pull-request-number }}"
          if [ -z "$PR_NUMBER" ]; then
            echo "No PR number found. Exiting."
            exit 1
          fi

          # NOTE: 先にマージしてから Approve すると auto merge によってマージされる
          gh pr merge -R "${{ github.repository }}" --squash --auto "$PR_NUMBER"
          gh pr review "$PR_NUMBER" --approve
